[project]
name = "jufdea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "auto-py-to-exe",
    "fpdf",
    "frontend",
    "pikepdf",
    "pymupdf",
    "pyqt6",
    "pyqt6-tools>=6.4.2.3.3",
]
